[input]
html_selector = "main"
base_directory = "D:\\Priyanshu Bishnoi\\Tech-blog\\blogs\\output"

[[input.files]]
path = "dll-system-design.html"
url = "/dll-system-design.html"
title = "DLLs - The Hidden System Design Boundaries"

[[input.files]]
path = "inheritance-oop.html"
url = "/inheritance-oop.html"
title = "Inheritance in Object-Oriented Programming"

[[input.files]]
path = "cap-atm.html"
url = "/cap-atm.html"
title = "CAP Theorem Meets ATMs"
